"""
Report stage - Markdown generation and Telegram notifications.
"""

import asyncio
import logging
import re
from datetime import UTC, datetime
from pathlib import Path

import httpx

from ..config import get_audit_dir, get_chain_config, settings
from ..models import (
    AuditReport,
    AuditResult,
    Chain,
    FindingsCount,
    Severity,
    VulnerabilityFinding,
)

log = logging.getLogger(__name__)

# Severity emojis
SEVERITY_EMOJI = {
    Severity.CRITICAL: "🔴",
    Severity.HIGH: "🟠",
    Severity.MEDIUM: "🟡",
    Severity.LOW: "🔵",
    Severity.INFO: "⚪",
}


def get_report_filename() -> str:
    """Generate markdown report filename."""
    return "final.md"


def generate_report_markdown(report: AuditReport) -> str:
    """Generate markdown report content."""
    chain_config = get_chain_config(report.chain.value)
    explorer_url = f"{chain_config.explorer_url}/address/{report.address}"

    md = f"""# Audit Report: {report.address}

## Summary

| Field | Value |
|-------|-------|
| **Address** | [`{report.address}`]({explorer_url}) |
| **Chain** | {chain_config.name} |
| **Started** | {report.started_at} |
| **Completed** | {report.completed_at} |
| **Status** | {report.status.value.upper()} |
| **RAG Context** | {"Yes" if report.rag_context_used else "No"} |

## Findings Summary

| Severity | Count |
|----------|-------|
| {SEVERITY_EMOJI[Severity.CRITICAL]} Critical | {report.findings_count.critical} |
| {SEVERITY_EMOJI[Severity.HIGH]} High | {report.findings_count.high} |
| {SEVERITY_EMOJI[Severity.MEDIUM]} Medium | {report.findings_count.medium} |
| {SEVERITY_EMOJI[Severity.LOW]} Low | {report.findings_count.low} |
| {SEVERITY_EMOJI[Severity.INFO]} Info | {report.findings_count.info} |

"""

    if report.total_profit_usd:
        md += f"**Estimated Total Profit**: ${report.total_profit_usd:,.2f}\n\n"

    if not report.findings:
        md += "## Findings\n\nNo vulnerabilities found.\n"
    else:
        md += "## Findings\n\n"

        for finding in report.findings:
            md += f"""### {SEVERITY_EMOJI[finding.severity]} {finding.title}

**ID**: `{finding.id}`
**Type**: {finding.type.value}
**Severity**: {finding.severity.value.upper()}
**Confidence**: {finding.confidence * 100:.0f}%
**Source**: {finding.source.value}
**Verified**: {"Yes" if finding.verified else "No"}

#### Description

{finding.description}

#### Impact

{finding.impact}

"""

            if finding.location.function or finding.location.selector:
                md += f"""#### Location

- **Function**: {finding.location.function or "Unknown"}
- **Selector**: `{finding.location.selector or "N/A"}`
{f"- **Line**: {finding.location.line}" if finding.location.line else ""}

"""

            if finding.exploit_scenario:
                md += f"""#### Exploit Scenario

{finding.exploit_scenario}

"""

            if finding.estimated_profit:
                md += f"""#### Estimated Profit

${finding.estimated_profit:,.2f}

"""

            if finding.poc_code:
                md += f"""#### PoC Code

```solidity
{finding.poc_code}
```

"""

            md += "---\n\n"

    if report.error_message:
        md += f"## Errors\n\n```\n{report.error_message}\n```\n"

    md += "\n---\n*Generated by Smart Contract Audit Pipeline*\n"

    return md


def save_report(report: AuditReport) -> str:
    """Save report to file."""
    audit_dir = get_audit_dir(report.chain.value, report.address)
    reports_dir = audit_dir / "reports"
    reports_dir.mkdir(parents=True, exist_ok=True)

    filename = get_report_filename()
    filepath = reports_dir / filename
    content = generate_report_markdown(report)

    filepath.write_text(content)
    log.info("Report saved: %s", filepath)

    return str(filepath)


async def send_telegram_message(text: str, parse_mode: str = "Markdown") -> bool:
    """Send text message via Telegram."""
    bot_token = settings.telegram_bot_token
    chat_id = settings.telegram_chat_id

    if not bot_token or not chat_id:
        log.debug("Telegram not configured, skipping notification")
        return False

    for attempt in range(3):
        try:
            async with httpx.AsyncClient(timeout=30) as client:
                response = await client.post(
                    f"https://api.telegram.org/bot{bot_token}/sendMessage",
                    json={
                        "chat_id": chat_id,
                        "text": text,
                        "parse_mode": parse_mode,
                        "disable_web_page_preview": True,
                    },
                )

                data = response.json()
                if data.get("ok"):
                    return True

                log.warning(
                    "Telegram error (attempt %d): %s",
                    attempt + 1,
                    data.get("description"),
                )

        except Exception as e:
            log.warning("Telegram request failed (attempt %d): %s", attempt + 1, e)

        if attempt < 2:
            await asyncio.sleep(1 * (attempt + 1))

    return False


async def send_telegram_document(filepath: str, caption: str) -> bool:
    """Send document (MD file) via Telegram."""
    bot_token = settings.telegram_bot_token
    chat_id = settings.telegram_chat_id

    if not bot_token or not chat_id:
        log.debug("Telegram not configured, skipping document upload")
        return False

    file_path = Path(filepath)
    if not file_path.exists():
        log.warning("File not found: %s", filepath)
        return False

    for attempt in range(3):
        try:
            async with httpx.AsyncClient(timeout=60) as client:
                file_bytes = await asyncio.to_thread(file_path.read_bytes)
                response = await client.post(
                    f"https://api.telegram.org/bot{bot_token}/sendDocument",
                    data={
                        "chat_id": chat_id,
                        "caption": caption,
                        "parse_mode": "Markdown",
                    },
                    files={"document": (file_path.name, file_bytes, "text/markdown")},
                )

                data = response.json()
                if data.get("ok"):
                    return True

                log.warning(
                    "Telegram sendDocument error (attempt %d): %s",
                    attempt + 1,
                    data.get("description"),
                )

        except Exception as e:
            log.warning("Telegram sendDocument failed (attempt %d): %s", attempt + 1, e)

        if attempt < 2:
            await asyncio.sleep(1 * (attempt + 1))

    return False


def escape_markdown(text: str) -> str:
    """Escape special characters for Telegram MarkdownV2."""
    if not text:
        return ""
    return re.sub(r"[_*\[\]()~`>#+=|{}.!\\-]", r"\\\g<0>", text)


def build_short_caption(report: AuditReport) -> str:
    """Build short caption for Telegram document (max 1024 chars)."""
    chain_config = get_chain_config(report.chain.value)

    lines = [
        "🚨 VULNERABILITY FOUND",
        "",
        f"Address: `{report.address}`",
        f"Chain: {chain_config.name}",
    ]

    if report.findings_count.critical > 0:
        lines.append(f"🔴 Critical: {report.findings_count.critical}")
    if report.findings_count.high > 0:
        lines.append(f"🟠 High: {report.findings_count.high}")
    if report.findings_count.medium > 0:
        lines.append(f"🟡 Medium: {report.findings_count.medium}")
    if report.findings_count.low > 0:
        lines.append(f"🔵 Low: {report.findings_count.low}")

    if report.total_profit_usd:
        lines.append(f"💰 Est. Profit: ${report.total_profit_usd:,.0f}")

    # PoC verification stats
    verified = [f for f in report.findings if f.verified]
    critical = [f for f in report.findings if f.severity == Severity.CRITICAL]
    if critical:
        lines.append(f"🧪 PoC: {len(verified)}/{len(critical)} verified")

    # Add top finding titles
    top_findings = report.findings[:2]
    if top_findings:
        lines.append("")
        lines.append("Top findings:")
        for f in top_findings:
            title = f.title[:40]
            lines.append(f"• [{f.severity.value.upper()[:4]}] {title}")

    return "\n".join(lines)[:1000]


async def send_critical_alert(report: AuditReport, report_path: str) -> bool:
    """Send critical audit alert with report attachment."""
    caption = build_short_caption(report)
    return await send_telegram_document(report_path, caption)


async def send_clean_audit_notification(address: str, chain: Chain) -> bool:
    """Send clean audit notification."""
    chain_config = get_chain_config(chain.value)
    message = (
        f"✅ *AUDIT COMPLETE (Clean)*\n\n"
        f"*Address*: `{address}`\n"
        f"*Chain*: {chain_config.name}\n\n"
        f"No vulnerabilities found."
    )
    return await send_telegram_message(message)


async def send_error_notification(address: str, chain: Chain, error: str) -> bool:
    """Send audit error notification."""
    chain_config = get_chain_config(chain.value)
    message = (
        f"⚠️ *AUDIT ERROR*\n\n"
        f"*Address*: `{address}`\n"
        f"*Chain*: {chain_config.name}\n\n"
        f"Error: {error[:200]}"
    )
    return await send_telegram_message(message)


async def send_poc_results(
    address: str,
    chain: Chain,
    findings: list[VulnerabilityFinding],
) -> bool:
    """Send PoC verification results to Telegram."""
    verified = [f for f in findings if f.verified]
    critical = [f for f in findings if f.severity == Severity.CRITICAL]
    failed = [f for f in critical if not f.verified]

    if not critical:
        return False  # Nothing to report

    chain_config = get_chain_config(chain.value)
    short_addr = f"{address[:6]}...{address[-4:]}"

    lines = [
        "🧪 *PoC Verification Complete*",
        "",
        f"Contract: `{short_addr}`",
        f"Chain: {chain_config.name}",
        "",
        f"Results: *{len(verified)}/{len(critical)}* exploitable",
    ]

    if verified:
        lines.append("")
        lines.append("✅ *Verified Exploits:*")
        for f in verified[:5]:  # Limit to 5
            title = f.title[:45] if len(f.title) > 45 else f.title
            lines.append(f"• {title}")

    if failed and len(failed) <= 5:
        lines.append("")
        lines.append("❌ *Not Exploitable:*")
        for f in failed:
            title = f.title[:45] if len(f.title) > 45 else f.title
            lines.append(f"• {title}")
    elif failed:
        lines.append("")
        lines.append(f"❌ *Not Exploitable:* {len(failed)} findings")

    return await send_telegram_message("\n".join(lines))


async def generate_initial_report(
    report: AuditReport,
    decompiled_code: str = "",
) -> tuple[str, bool]:
    """
    Generate initial report with optional PoC button for CRITICAL findings.

    This is the first report sent after ANALYZE stage.
    If CRITICAL findings exist, includes a button to trigger PoC verification.

    Args:
        report: Audit report object
        decompiled_code: Decompiled contract code for PoC generation

    Returns:
        (report_path, notified)
    """
    # Save report
    report_path = save_report(report)

    # Send notification based on status
    notified = False

    if report.status == AuditResult.VULNERABLE:
        has_critical = report.findings_count.critical > 0
        has_high = report.findings_count.high > 0

        if has_critical:
            # Use new telegram_bot with PoC button
            try:
                from ..telegram_bot import send_initial_report as send_with_button

                success, _ = await send_with_button(
                    report, report_path, decompiled_code
                )
                notified = success
            except ImportError:
                # Fallback to old method if telegram_bot not available
                notified = await send_critical_alert(report, report_path)

        elif has_high:
            # HIGH findings without PoC button
            notified = await send_critical_alert(report, report_path)
        else:
            # Medium/Low findings - text notification
            chain_config = get_chain_config(report.chain.value)
            message = (
                f"🔍 *Vulnerability Found*\n\n"
                f"*Address*: `{report.address}`\n"
                f"*Chain*: {chain_config.name}\n"
                f"*Findings*: {len(report.findings)} (Medium/Low)\n\n"
                f"Report saved: {Path(report_path).name}"
            )
            notified = await send_telegram_message(message)

    elif report.status == AuditResult.CLEAN:
        # Don't spam Telegram with clean audits
        log.debug(
            "Clean audit for %s - skipping Telegram notification", report.address[:16]
        )
        notified = False

    elif report.status == AuditResult.ERROR:
        notified = await send_error_notification(
            report.address, report.chain, report.error_message or "Unknown error"
        )

    return report_path, notified


async def generate_and_notify(report: AuditReport) -> tuple[str, bool]:
    """
    Full report flow: generate, save, and notify.

    DEPRECATED: Use generate_initial_report() for new code.
    Kept for backward compatibility.
    """
    return await generate_initial_report(report, decompiled_code="")


def build_report(
    address: str,
    chain: Chain,
    started_at: datetime | str,
    status: AuditResult,
    findings: list[VulnerabilityFinding],
    rag_context_used: bool,
    error_message: str | None = None,
) -> AuditReport:
    """Build audit report object."""
    findings_count = FindingsCount(
        critical=sum(1 for f in findings if f.severity == Severity.CRITICAL),
        high=sum(1 for f in findings if f.severity == Severity.HIGH),
        medium=sum(1 for f in findings if f.severity == Severity.MEDIUM),
        low=sum(1 for f in findings if f.severity == Severity.LOW),
        info=sum(1 for f in findings if f.severity == Severity.INFO),
    )

    total_profit = sum(f.estimated_profit or 0 for f in findings)
    started_at_dt = (
        datetime.fromisoformat(started_at) if isinstance(started_at, str) else started_at
    )

    return AuditReport(
        address=address,
        chain=chain,
        startedAt=started_at_dt,
        completedAt=datetime.now(UTC),
        findings=findings,
        findingsCount=findings_count,
        totalProfitUsd=total_profit if total_profit > 0 else None,
        status=status,
        errorMessage=error_message,
        ragContextUsed=rag_context_used,
    )
