"""Evidence-gated autoresearch primitives for closed-source EVM audits."""

from .artifact import (
    build_artifact_bundle,
    load_artifact_bundle,
    opcode_listing,
    write_artifact_bundle,
    write_opcode_listing,
)
from .loop import (
    load_hypotheses_file,
    passes_consensus_gate,
    plan_goals,
    run_offline_research_loop,
)
from .memory import load_rejected_memory, rejected_memory_from_state, write_rejected_memory
from .model_runner import (
    ModelHandoffResult,
    OpenAICompatibleConfig,
    extract_json_object,
    generate_model_hypotheses,
    parse_hypotheses_payload,
)
from .models import (
    ArtifactBundle,
    AttackHypothesis,
    AuditGoal,
    AutoresearchInternalReport,
    ConsensusDecision,
    HypothesisStatus,
    LoopReceipt,
    LoopScratchpad,
    MaterialRef,
    RejectedHypothesisSummary,
    ResearchLoopState,
    SnapshotContext,
    SpecialistDomain,
    StuckSignal,
    ValidationMethod,
    ValidationResult,
    ValidationStatus,
    ValidatorKind,
    VerificationPackage,
)
from .report import write_internal_report
from .tools import (
    build_cheap_fact_index,
    build_cheap_tool_manifest,
    collect_materialized_facts,
    materialize_cheap_tool_artifacts,
    write_cheap_fact_index,
    write_cheap_tool_artifacts,
)
from .validator import (
    validate_economic_package,
    validate_foundry_package,
    validate_ityfuzz_package,
    validate_package,
    validate_property_package,
    validate_symbolic_package,
)
from .verification import write_verification_package

__all__ = [
    "ArtifactBundle",
    "AutoresearchInternalReport",
    "AttackHypothesis",
    "AuditGoal",
    "ConsensusDecision",
    "HypothesisStatus",
    "LoopReceipt",
    "LoopScratchpad",
    "MaterialRef",
    "ModelHandoffResult",
    "OpenAICompatibleConfig",
    "RejectedHypothesisSummary",
    "ResearchLoopState",
    "SnapshotContext",
    "SpecialistDomain",
    "StuckSignal",
    "ValidationResult",
    "ValidationStatus",
    "ValidatorKind",
    "ValidationMethod",
    "VerificationPackage",
    "build_artifact_bundle",
    "build_cheap_fact_index",
    "build_cheap_tool_manifest",
    "collect_materialized_facts",
    "extract_json_object",
    "generate_model_hypotheses",
    "load_artifact_bundle",
    "load_hypotheses_file",
    "load_rejected_memory",
    "opcode_listing",
    "passes_consensus_gate",
    "parse_hypotheses_payload",
    "plan_goals",
    "rejected_memory_from_state",
    "run_offline_research_loop",
    "materialize_cheap_tool_artifacts",
    "write_artifact_bundle",
    "write_cheap_fact_index",
    "write_cheap_tool_artifacts",
    "write_internal_report",
    "write_opcode_listing",
    "validate_foundry_package",
    "validate_economic_package",
    "validate_ityfuzz_package",
    "validate_package",
    "validate_property_package",
    "validate_symbolic_package",
    "write_rejected_memory",
    "write_verification_package",
]
